import { generateKeyPairSync, sign, type KeyObject } from "node:crypto";
import { describe, expect, it } from "vitest";

import {
  canonicalPayload,
  createEnrolment,
  fingerprintFromPublicKey,
  nextState,
  verifySignature,
} from "../../scripts/registry/enrolment.mjs";
import { createStore, entryId } from "../../scripts/registry/store.mjs";

// Real key material generated by `ssh-keygen -t ed25519`, kept as a fixture so
// the fingerprint below is what `ssh-keygen -lf` prints for the same key.
const SSH_KEYGEN_PUBKEY =
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB4C5Hf3OlfN7MEBIAWk6D03X5smw8KB/dDHhfhiX6Re registry-fixture";
const SSH_KEYGEN_FINGERPRINT =
  "SHA256:8NeiIgzltMXycwvv3RnvRhfFAVAiqHx+kkUgfMYO2iA";

type Entry = Record<string, unknown> & { id: string; state: string };

/** Minimal in-memory provider; the real one is exercised in routes.test.ts. */
function createMemoryProvider(): {
  list: () => Promise<Entry[]>;
  upsert: (entry: Entry) => Promise<Entry>;
  remove: (id: string) => Promise<void>;
  setState: (id: string, state: string) => Promise<Entry>;
} {
  const entries = new Map<string, Entry>();
  return {
    async list() {
      return [...entries.values()];
    },
    async upsert(entry) {
      entries.set(entry.id, entry);
      return entry;
    },
    async remove(id) {
      entries.delete(id);
    },
    async setState(id, state) {
      const entry = entries.get(id);
      if (!entry) throw new Error(`no entry ${id}`);
      const updated = { ...entry, state };
      entries.set(id, updated);
      return updated;
    },
  };
}

function sshPublicKeyLine(publicKey: KeyObject) {
  // SPKI DER for Ed25519 is a 12-byte header followed by the 32 raw key bytes.
  const raw = publicKey.export({ format: "der", type: "spki" }).subarray(12);
  const type = Buffer.from("ssh-ed25519", "utf8");
  const blob = Buffer.concat([
    Buffer.from([0, 0, 0, type.length]),
    type,
    Buffer.from([0, 0, 0, raw.length]),
    raw,
  ]);
  return `ssh-ed25519 ${blob.toString("base64")} test@fixture`;
}

function makeHostKey() {
  const { publicKey, privateKey } = generateKeyPairSync("ed25519");
  return { pubkey: sshPublicKeyLine(publicKey), privateKey };
}

const NOW_MS = Date.parse("2026-09-04T10:00:00.000Z");

function makeBody(pubkey: string, overrides: Record<string, unknown> = {}) {
  return {
    name: "hetzner",
    host: "https://claude-hetzner.example.ts.net:8443",
    pubkey,
    credRef: "openhands/hetzner/session-key",
    version: "1.44.0",
    nonce: "nonce-1",
    ts: Math.floor(NOW_MS / 1000),
    ...overrides,
  };
}

function signBody(body: Record<string, unknown>, privateKey: KeyObject) {
  return sign(
    null,
    Buffer.from(canonicalPayload(body), "utf8"),
    privateKey,
  ).toString("base64");
}

function makeEnrolment(allowlist: string[] = []) {
  const store = createStore(createMemoryProvider());
  const enrolment = createEnrolment({
    store,
    allowlist,
    now: () => NOW_MS,
  });
  return { store, enrolment };
}

describe("fingerprintFromPublicKey", () => {
  it("matches what ssh-keygen -lf prints for the same key", () => {
    expect(fingerprintFromPublicKey(SSH_KEYGEN_PUBKEY)).toBe(
      SSH_KEYGEN_FINGERPRINT,
    );
  });

  it("ignores the trailing comment", () => {
    const withoutComment = SSH_KEYGEN_PUBKEY.split(" ").slice(0, 2).join(" ");
    expect(fingerprintFromPublicKey(withoutComment)).toBe(
      SSH_KEYGEN_FINGERPRINT,
    );
  });

  it("rejects a key that is not ssh-ed25519", () => {
    expect(() => fingerprintFromPublicKey("ssh-rsa AAAAB3Nza")).toThrowError(
      /ssh-ed25519/,
    );
  });
});

describe("canonicalPayload", () => {
  it("is stable across key order", () => {
    const pubkey = SSH_KEYGEN_PUBKEY;
    const a = canonicalPayload({
      name: "a",
      host: "h",
      pubkey,
      nonce: "n",
      ts: 1,
    });
    const b = canonicalPayload({
      ts: 1,
      nonce: "n",
      pubkey,
      host: "h",
      name: "a",
    });
    expect(a).toBe(b);
  });

  it("treats an omitted optional field the same as an explicit null", () => {
    const base = { name: "a", host: "h", pubkey: "p", nonce: "n", ts: 1 };
    expect(canonicalPayload({ ...base, credRef: null })).toBe(
      canonicalPayload(base),
    );
  });

  it("does not cover unknown fields", () => {
    const base = { name: "a", host: "h", pubkey: "p", nonce: "n", ts: 1 };
    expect(canonicalPayload({ ...base, state: "active" })).toBe(
      canonicalPayload(base),
    );
  });
});

describe("verifySignature", () => {
  it("accepts a signature made with the matching private key", () => {
    const { pubkey, privateKey } = makeHostKey();
    const body = makeBody(pubkey);
    expect(verifySignature(body, signBody(body, privateKey))).toBe(true);
  });

  it("rejects a signature made with a different key", () => {
    const { pubkey } = makeHostKey();
    const other = makeHostKey();
    const body = makeBody(pubkey);
    expect(verifySignature(body, signBody(body, other.privateKey))).toBe(false);
  });

  it("rejects a signature over different content", () => {
    const { pubkey, privateKey } = makeHostKey();
    const signature = signBody(makeBody(pubkey), privateKey);
    const tampered = makeBody(pubkey, { host: "https://attacker.example" });
    expect(verifySignature(tampered, signature)).toBe(false);
  });

  it("rejects a signature of the wrong length", () => {
    const { pubkey } = makeHostKey();
    expect(verifySignature(makeBody(pubkey), "c2hvcnQ=")).toBe(false);
  });
});

describe("nextState", () => {
  it("keeps a revoked entry revoked even when it re-enrols pre-seeded", () => {
    expect(nextState({ state: "revoked" }, true)).toBe("revoked");
  });

  it("keeps an approved entry active once its fingerprint is un-seeded", () => {
    expect(nextState({ state: "active" }, false)).toBe("active");
  });

  it("promotes a pending entry only for a pre-seeded fingerprint", () => {
    expect(nextState({ state: "pending" }, true)).toBe("active");
    expect(nextState({ state: "pending" }, false)).toBe("pending");
  });
});

describe("createEnrolment().register", () => {
  it("lands an unknown fingerprint in the pending TOFU queue", async () => {
    const { pubkey, privateKey } = makeHostKey();
    const { enrolment, store } = makeEnrolment();
    const body = makeBody(pubkey);

    const { entry, created } = await enrolment.register(
      body,
      signBody(body, privateKey),
    );

    expect(created).toBe(true);
    expect(entry.state).toBe("pending");
    expect(entry.fingerprint).toBe(fingerprintFromPublicKey(pubkey));
    expect(entry.id).toBe(entryId(entry.fingerprint));
    expect(entry.credRef).toBe("openhands/hetzner/session-key");
    expect(entry.lastSeen).toBe(new Date(NOW_MS).toISOString());
    expect(await store.list()).toHaveLength(1);
  });

  it("auto-approves a pre-seeded fingerprint", async () => {
    const { pubkey, privateKey } = makeHostKey();
    const { enrolment } = makeEnrolment([fingerprintFromPublicKey(pubkey)]);
    const body = makeBody(pubkey);

    const { entry } = await enrolment.register(
      body,
      signBody(body, privateKey),
    );

    expect(entry.state).toBe("active");
  });

  it("accepts a pre-seeded fingerprint written without the SHA256: prefix", async () => {
    const { pubkey, privateKey } = makeHostKey();
    const bare = fingerprintFromPublicKey(pubkey).replace("SHA256:", "");
    const { enrolment } = makeEnrolment([bare]);
    const body = makeBody(pubkey);

    const { entry } = await enrolment.register(
      body,
      signBody(body, privateKey),
    );

    expect(entry.state).toBe("active");
  });

  it("rejects a signature from the wrong key", async () => {
    const { pubkey } = makeHostKey();
    const other = makeHostKey();
    const { enrolment, store } = makeEnrolment();
    const body = makeBody(pubkey);

    await expect(
      enrolment.register(body, signBody(body, other.privateKey)),
    ).rejects.toMatchObject({ status: 401, code: "invalid_signature" });
    expect(await store.list()).toHaveLength(0);
  });

  it("rejects a replayed nonce", async () => {
    const { pubkey, privateKey } = makeHostKey();
    const { enrolment } = makeEnrolment();
    const body = makeBody(pubkey);
    const signature = signBody(body, privateKey);

    await enrolment.register(body, signature);

    await expect(enrolment.register(body, signature)).rejects.toMatchObject({
      status: 401,
      code: "replayed_nonce",
    });
  });

  it("rejects a stale timestamp", async () => {
    const { pubkey, privateKey } = makeHostKey();
    const { enrolment } = makeEnrolment();
    const body = makeBody(pubkey, { ts: Math.floor(NOW_MS / 1000) - 301 });

    await expect(
      enrolment.register(body, signBody(body, privateKey)),
    ).rejects.toMatchObject({ status: 401, code: "stale_timestamp" });
  });

  it("rejects a timestamp sent in milliseconds", async () => {
    const { pubkey, privateKey } = makeHostKey();
    const { enrolment } = makeEnrolment();
    const body = makeBody(pubkey, { ts: NOW_MS });

    await expect(
      enrolment.register(body, signBody(body, privateKey)),
    ).rejects.toMatchObject({ status: 401, code: "stale_timestamp" });
  });

  it("does not record a nonce for a registration it rejected", async () => {
    const { pubkey, privateKey } = makeHostKey();
    const other = makeHostKey();
    const { enrolment } = makeEnrolment();
    const body = makeBody(pubkey);

    await expect(
      enrolment.register(body, signBody(body, other.privateKey)),
    ).rejects.toMatchObject({ code: "invalid_signature" });

    const { entry } = await enrolment.register(
      body,
      signBody(body, privateKey),
    );
    expect(entry.state).toBe("pending");
  });

  it("updates the existing entry when the same fingerprint re-registers", async () => {
    const { pubkey, privateKey } = makeHostKey();
    const { enrolment, store } = makeEnrolment();

    const first = makeBody(pubkey);
    await enrolment.register(first, signBody(first, privateKey));

    const second = makeBody(pubkey, {
      name: "hetzner-renamed",
      host: "https://claude-hetzner.example.ts.net:9443",
      version: "1.45.0",
      nonce: "nonce-2",
    });
    const { entry, created } = await enrolment.register(
      second,
      signBody(second, privateKey),
    );

    expect(created).toBe(false);
    expect(await store.list()).toHaveLength(1);
    expect(entry.name).toBe("hetzner-renamed");
    expect(entry.host).toBe("https://claude-hetzner.example.ts.net:9443");
    expect(entry.version).toBe("1.45.0");
  });

  it("cannot resurrect a revoked entry by re-registering", async () => {
    const { pubkey, privateKey } = makeHostKey();
    const fingerprint = fingerprintFromPublicKey(pubkey);
    const { enrolment, store } = makeEnrolment([fingerprint]);

    const first = makeBody(pubkey);
    const { entry } = await enrolment.register(
      first,
      signBody(first, privateKey),
    );
    await store.setState(entry.id, "revoked");

    const second = makeBody(pubkey, { nonce: "nonce-2" });
    const { entry: reRegistered } = await enrolment.register(
      second,
      signBody(second, privateKey),
    );

    expect(reRegistered.state).toBe("revoked");
  });

  it("rejects a host that is not an http(s) URL", async () => {
    const { pubkey, privateKey } = makeHostKey();
    const { enrolment } = makeEnrolment();
    const body = makeBody(pubkey, { host: "file:///etc/passwd" });

    await expect(
      enrolment.register(body, signBody(body, privateKey)),
    ).rejects.toMatchObject({ status: 400, code: "invalid_field" });
  });

  it("rejects a body missing a required field before checking the signature", async () => {
    const { pubkey, privateKey } = makeHostKey();
    const { enrolment } = makeEnrolment();
    const body = makeBody(pubkey, { nonce: "" });

    await expect(
      enrolment.register(body, signBody(body, privateKey)),
    ).rejects.toMatchObject({ status: 400, code: "invalid_body" });
  });
});
